/* Graphite component tokens (docs/theme-direction.md).
   Generated by omarchy-theme-set from ~/.config/omarchy/themed/graphite.css.tpl.
   Colors come from the theme's colors.toml. A theme without a token gets the
   nearest standard key. */
:root {
  --token-source: theme;
  --surface-0: {{ shell_gradient surface_0 darker_background }};
  --surface-1: {{ shell_gradient surface_1 background }};
  --surface-2: {{ shell_gradient surface_2 lighter_background }};
  --surface-3: {{ shell_gradient surface_3 muted }};
  --lift: {{ shell_gradient lift muted }};
  --text-1: {{ shell_gradient text_1 bright_foreground }};
  --text-2: {{ shell_gradient text_2 foreground }};
  --text-3: {{ shell_gradient text_3 light_foreground }};
  --text-4: {{ shell_gradient text_4 dark_foreground }};
  --accent: {{ accent }};
  --accent-soft: {{ shell_gradient accent_soft bright_blue }};
  --on-accent: {{ shell_gradient on_accent darker_background }};
  --label-tint: {{ shell_gradient label_tint light_foreground }};
  --ok: {{ shell_gradient ok green }};
  --warn: {{ shell_gradient warn yellow }};
  --error: {{ shell_gradient error red }};
  --keycap-edge: {{ shell_gradient keycap_edge rgba(255,255,255,0.14) }};
  --highlight: {{ shell_gradient highlight rgba(255,255,255,0.06) }};

  --radius-panel: 16px;
  --radius-group: 8px;
  --radius-row: 6px;
  --radius-field: 5px;
  --shadow-panel: inset 0 1px 0 var(--highlight), 0 20px 48px rgba(0, 0, 0, 0.55);
  --shadow-lift: inset 0 1px 0 var(--highlight), 0 2px 8px rgba(0, 0, 0, 0.4);

  --pad-panel: 16px;
  --pad-group: 4px;
  --gap-row: 2px;
  --gap-group: 10px;
  --row-nav: 36px;
  --row-data: 30px;
  --row-group-name: 26px;

  --font-label: "SF Pro Text", "SF Pro", system-ui, sans-serif;
  --font-value: "SF Mono", "SFMono Nerd Font Mono", ui-monospace, monospace;
}
