-- Fixed workspaces for each kind of work.
--
--   1  Agents         T3 Code, Claude
--   2  Project        Agent sessions and sites for a project
--   3  Project        Agent sessions and sites for another project
--   4  Design         Figma, Paper, Claude Design
--   5  Web            Normal browsing
--   6  Messages       HEY, WhatsApp, Discord, Signal, Google Messages
--
-- Apps below open on their workspace. Projects get their workspace from
-- ~/.config/omarchy/projects.json: the Projects menu (Super+D) opens sessions
-- there, and projects-apply writes the rules for their sites to hypr/projects.lua.

-- Keep workspaces 1-6 in the bar, also when they are empty.
for workspace = 1, 6 do
  hl.workspace_rule({ workspace = tostring(workspace), persistent = true })
end

-- 1  Agents
o.window("^com\\.t3tools\\.T3Code$", { workspace = "1" })
o.window("^chrome-claude\\.ai__new-Default$", { workspace = "1" })

-- 4  Design
local design_apps = "^chrome-(claude\\.ai__design|www\\.figma\\.com__.*|app\\.paper\\.design__.*)-Default$"
o.window(design_apps, { workspace = "4" })

-- Design apps are fully opaque, also when not focused, so colors show correctly.
o.window(design_apps, { tag = "-default-opacity" })
o.window(design_apps, { opacity = "1 1" })

-- 6  Messages
o.window("^chrome-(app\\.hey\\.com|web\\.whatsapp\\.com|discord\\.com|messages\\.google\\.com)__.*-Default$", { workspace = "6" })
o.window("^signal$", { workspace = "6" })


-- Project sites, generated by projects-apply. The file is optional.
pcall(require, "hypr.projects")
